networks:
  sdg_internal:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
  sdg_external:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
  monitoring_network:
    driver: bridge
    internal: true

services:
  nginx_proxy:
    image: nginx:1.25-alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/ssl/certs:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - sdg_external
      - sdg_internal
    depends_on:
      auth_service:
        condition: service_healthy
      api_service:
        condition: service_healthy
    environment:
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  auth_service:
    build:
      context: ${SRC_ROOT}
      dockerfile: auth/Dockerfile
    container_name: auth_service
    expose:
      - "8005"
    volumes:
      - ${SRC_ROOT}:/app/src:ro
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
      - SECRET_KEY_ENCRYPTED=${SECRET_KEY_ENCRYPTED:-}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_URL_ENCRYPTED=${DATABASE_URL_ENCRYPTED:-}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - ENVIRONMENT=${ENVIRONMENT}
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    networks:
      - sdg_internal
    depends_on:
      database_service:
        condition: service_healthy
      db_bootstrap:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    command: ["python", "-m", "uvicorn", "src.auth.main:app", "--host", "0.0.0.0", "--port", "8005"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  api_service:
    build:
      context: ${SRC_ROOT}
      dockerfile: api/Dockerfile
      args:
        - BUILD_ENV=production
    container_name: api_service
    restart: unless-stopped
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ${SRC_ROOT}:/app/src:ro
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - WEAVIATE_URL=${WEAVIATE_URL}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - LOG_LEVEL=INFO
      - WORKERS=4
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    networks:
      - sdg_internal
    depends_on:
      database_service:
        condition: service_healthy
      db_bootstrap:
        condition: service_completed_successfully
      auth_service:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: python -m uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
        reservations:
          cpus: "1.0"
          memory: 1G

  database_service:
    image: postgres:16-alpine
    container_name: database_service
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-sdg_pipeline}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=en_US.UTF-8
      - POSTGRES_SHARED_PRELOAD_LIBRARIES=pg_stat_statements
      - POSTGRES_MAX_CONNECTIONS=200
      - POSTGRES_SHARED_BUFFERS=256MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=1GB
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    volumes:
      - ${DATABASE_SERVICE_VOLUMES}
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
      - ./postgres/backup:/backup
    networks:
      - sdg_internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4G
        reservations:
          cpus: "1.0"
          memory: 2G

  db_bootstrap:
    image: postgres:16-alpine
    depends_on:
      database_service:
        condition: service_healthy
    environment:
      - PGHOST=database_service
      - PGPORT=5432
      - PGUSER=${POSTGRES_USER:-postgres}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - APP_DB_NAME=${POSTGRES_DB:-sdg_pipeline}
      - APP_DB_USER=sdg_service
      - APP_DB_PASSWORD=${APP_DB_PASSWORD}
    volumes:
      - /mnt/gigabyte1tb/SDG/sdg_root/src/api/bootstrap.sql:/bootstrap/bootstrap.sql:ro
    command:
      - sh
      - -lc
      - >
        set -euo pipefail;
        psql -h "${PGHOST}" -U "${PGUSER}" -d postgres -v ON_ERROR_STOP=1
        -v u="${APP_DB_USER}" -v d="${APP_DB_NAME}" -v p="${APP_DB_PASSWORD}"
        -f /bootstrap/bootstrap.sql
    restart: "no"
    networks:
      - sdg_internal
  
  weaviate_service:
    image: semitechnologies/weaviate:1.32.2
    container_name: weaviate_service
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=false
      - AUTHENTICATION_APIKEY_ENABLED=true
      - AUTHENTICATION_APIKEY_ALLOWED_KEYS=${WEAVIATE_API_KEY}
      - AUTHENTICATION_APIKEY_USERS=sdg-admin
      - DEFAULT_VECTORIZER_MODULE=none
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - CLUSTER_HOSTNAME=node1
      - MODULES_CLIENT_TIMEOUT=600s
      - LIMIT_RESOURCES=true
      - GOMEMLIMIT=3GiB
      - GOGC=100
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    volumes:
      - ${WEAVIATE_SERVICE_VOLUMES}
    networks:
      - sdg_internal
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/.well-known/ready || exit 1"]
      interval: 45s
      timeout: 30s
      retries: 25
      start_period: 600s
    depends_on:
      weaviate_transformer_service:
        condition: service_healthy
      db_bootstrap:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 6G
        reservations:
          cpus: "2.0"
          memory: 3G

  weaviate_transformer_service:
    image: ${WEAVIATE_IMAGE}
    container_name: weaviate_transformer_service
    ports:
      - "8081:8080"
    environment:
      - ENABLE_GPU=0
      - TORCH_NUM_THREADS=4
      - OMP_NUM_THREADS=4
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8080/.well-known/ready\").read()' || exit 1"]
      interval: 45s
      timeout: 30s
      retries: 25
      start_period: 600s
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8G
        reservations:
          memory: 4G
    networks:
      - sdg_internal

  vectorization_service:
    build: ${SRC_ROOT}/vectorization
    container_name: vectorization_service
    ports:
      - "8003:8003"
    volumes:
      - ${SRC_ROOT}:/app/src:ro
    environment:
      - PYTHONPATH=/app
      - WEAVIATE_URL=${WEAVIATE_URL}
      - WEAVIATE_API_KEY=${WEAVIATE_API_KEY}
      - DATABASE_URL=${DATABASE_URL:-}
      - REDIS_URL=${REDIS_URL}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    depends_on:
      weaviate_service:
        condition: service_healthy
    command: python -m uvicorn src.vectorization.main:app --host 0.0.0.0 --port 8003
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    networks:
      - sdg_internal

  data_retrieval_service:
    build: ${SRC_ROOT}/data_retrieval
    container_name: data_retrieval_service
    ports:
      - "8002:8002"
    volumes:
      - ${SRC_ROOT}:/app/src:ro
      - ${DATA_ROOT}/raw_data:/app/raw_data
      - ${DATA_ROOT}/quelle.txt:/app/quelle.txt
    environment:
      - PYTHONPATH=/app
      - SERVICE_HOST=data_retrieval_service
      - SERVICE_PORT=8002
      - DATABASE_URL=${DATABASE_URL:-}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - SECRET_KEY=${SECRET_KEY}
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    depends_on:
      database_service:
        condition: service_healthy
      db_bootstrap:
        condition: service_completed_successfully
    command: ["python", "-m", "uvicorn", "src.data_retrieval.main:app", "--host", "0.0.0.0", "--port", "8002"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: "1.0"
    networks:
      - sdg_internal

  data_processing_service:
    build: ${SRC_ROOT}/data_processing
    container_name: data_processing_service
    ports:
      - "8001:8001"
    volumes:
      - ${SRC_ROOT}:/app/src:ro
      - ${DATA_ROOT}/raw_data:/app/raw_data
      - ${DATA_ROOT}/processed_data:/app/processed_data
      - ${DATA_ROOT}/images:/app/images
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=${DATABASE_URL:-}
      - WEAVIATE_URL=${WEAVIATE_URL}
      - WEAVIATE_API_KEY=${WEAVIATE_API_KEY}
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    depends_on:
      database_service:
        condition: service_healthy
      db_bootstrap:
        condition: service_completed_successfully
      weaviate_service:
        condition: service_healthy
      data_retrieval_service:
        condition: service_healthy
    command: python -m uvicorn src.data_processing.main:app --host 0.0.0.0 --port 8001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 45s
      timeout: 20s
      retries: 5
      start_period: 120s
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 4G
        reservations:
          cpus: "2"
          memory: 3G
    networks:
      - sdg_internal

  content_extraction_service:
    build: ${SRC_ROOT}/content_extraction
    container_name: content_extraction_service
    ports:
      - "8004:8004"
    volumes:
      - ${SRC_ROOT}:/app/src:ro
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=${DATABASE_URL:-}
      - WEAVIATE_URL=${WEAVIATE_URL}
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - SECRET_KEY=${SECRET_KEY}
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    depends_on:
      database_service:
          condition: service_healthy
      db_bootstrap:
          condition: service_completed_successfully
    command: python -m uvicorn src.content_extraction.main:app --host 0.0.0.0 --port 8004
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2G
    networks:
      - sdg_internal

  pgadmin_service:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_service
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    volumes:
      - ${PGADMIN_VOLUMES}
    depends_on:
      database_service:
        condition: service_healthy
    user: "5050:5050"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    networks:
      - sdg_internal

  weaviate_console:
    image: semitechnologies/weaviate-console
    container_name: weaviate_console
    ports:
      - "3001:3000"
    environment:
      - WEAVIATE_HOST=weaviate_service:8080
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    depends_on:
      weaviate_service:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    networks:
      - sdg_internal

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - sdg_internal
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} -h 127.0.0.1 -p 6379 ping | grep PONG"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  migration_service:
    build: ${SRC_ROOT}/migration
    container_name: migration_service
    command: python migration_plan.py
    depends_on:
      database_service:
        condition: service_healthy
    environment:
      - MIGRATION_MODE=production
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    networks:
      - sdg_internal

  monitoring_service:
    profiles: ["aux"]          # do not build by default
    build: ${SRC_ROOT}/monitoring
    container_name: monitoring_service
    ports:
      - "9090:9090"
    volumes:
      - ${SRC_ROOT}:/app/src
      - ${DATA_ROOT}:/app/data
    environment:
      - MIGRATION_MODE=production
      - LOG_LEVEL=INFO
      - PARALLEL_MIGRATIONS=true
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    depends_on:
      - api_service
      - data_processing_service
      - database_service
      - weaviate_service
      - redis
    networks:
      - sdg_internal
      - monitoring_network

  config_service:
    profiles: ["aux"]          # do not build by default
    build: ${SRC_ROOT}/config_manager
    container_name: config_service
    ports:
      - "8006:8006"
    volumes:
      - ${SRC_ROOT}/config:/app/config
    environment:
      - CONFIG_DIR=/app/config
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    networks:
      - sdg_internal

  error_handler_service:
    profiles: ["aux"]          # do not build by default
    build: ${SRC_ROOT}/error_handler
    container_name: error_handler_service
    ports:
      - "8007:8007"
    environment:
      - CIRCUIT_BREAKER_THRESHOLD=5
      - RECOVERY_TIMEOUT=60
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    networks:
      - sdg_internal

  url_validator_service:
    profiles: ["aux"]
    build: ${SRC_ROOT}/url_validator
    container_name: url_validator_service
    ports:
      - "8008:8008"
    environment:
      - VALIDATION_TIMEOUT=30
      - MAX_FILE_SIZE=52428800
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    networks:
      - sdg_internal

  testing_service:
    build: ${SRC_ROOT}/testing
    container_name: testing_service
    profiles: ["testing"]
    command: pytest --cov=src tests/
    volumes:
      - ${SRC_ROOT}:/app
    environment:
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    depends_on:
      database_service:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - sdg_internal

  backup_service:
    profiles: ["aux"]          # do not build by default
    build: ${SRC_ROOT}/backup
    container_name: backup_service
    volumes:
      - ${DATA_ROOT}:/data
      - ${BACKUP_ROOT}:/backup
    environment:
      - BACKUP_SCHEDULE=0 2 * * *
      - RETENTION_DAYS=30
      - DEPENDENCY_MANAGER_ENABLED=true
      - HEALTH_CHECK_INTERVAL=60
      - MAX_STARTUP_TIME=300
    networks:
      - sdg_internal

volumes:
  redis_data:
    driver: local

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  app_db_password:
    file: ./secrets/app_db_password.txt
  weaviate_api_key:
    file: ./secrets/weaviate_api_key.txt
