version: "3.9"
services:
  weaviate_transformer_service:
    ports:
      - "8081:8080"
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-weaviate-transformer:latest
    container_name: weaviate_transformer_service
    environment:
      - ENABLE_GPU=0
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/meta"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '8G'

